create table os_network_true_coverage_pro (
    report_start_date date encoding days(32),
    report_end_date date encoding days(32),
    network_name_mapped text encoding dict(8),
    parent_location text encoding dict(16),
    id text encoding dict,
    level_used integer,
    avail_impact double,
    avail_contribution double,
    avail_performance double,
    avail_importance double,
    avail_performance_diff_vs_target double,
    avail_performance_target double,
    lte_enbl_dev_avg_signal_2g double,
    lte_enbl_dev_avg_signal_3g double,
    lte_enbl_dev_avg_rsrp double,
    lte_enbl_dev_avg_rsrq double,
    lte_enbl_dev_avg_rssnr double,
    lte_enbl_dev_rows_2g_share double,
    lte_enbl_dev_rows_3g_share double,
    lte_enbl_dev_rows_lte_share double,
    lte_enbl_dev_rows_no_signal_share double,
    latitude double,
    longitude double
);